### ISSUE TITLE
在运行时出现opencv的错误

### ISSUE THREAD

**Issue by yuhuabing** [lixiny/ORB-SLAM2-DualCam#2]
我按照教程编译并运行，出现如下的opencv错误：
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/yhb/opencv/modules/imgproc/src/imgwarp.cpp, line 3492
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/yhb/opencv/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
经过调试发现是dual_slam_video.cpp中while循环的cap >> frame这句话运行的第20次出错：
请问怎么解决这个问题呢？

**Comment by lixiny** [comment]
我重新试了一下没有遇到这个问题， 我用的 OpenCV 版本是3.3（installed within ros-kinetic), 或许你可以在代码中加上 try catch 来跳过 openCV 的Exception，希望能帮到你。

**Comment by yuhuabing** [comment]
@lixiny  我调试好了学长，能问一下你的联系方式吗，我的毕业论文也是做相关的工作，想向您请教以下。

**Comment by lixiny** [comment]
Hi， 我主页有留edu mailbox， 你可以给我发邮件
