### ISSUE TITLE
只能用给定的视频进行测试嘛？

### ISSUE THREAD

**Issue by Mr-W-Bin** [lixiny/ORB-SLAM2-DualCam#3]

**Comment by lixiny** [comment]
是的，当前版本只支持在给定的dual camera model 和 indoor_lab_loop.avi 上进行测验；
如果你有自己的双视角相机，可以更改 [配置文件](https://github.com/lixiny/ORB-SLAM2-DualCam/blob/master/Dual-LenaCV.yaml) 中的相机参数（当前能想到的有 intrinsic，extrinsic）后 进行测试。
